### ISSUE TITLE
SPIKE - section vs article vs div

### ISSUE THREAD

**Issue by alexw1983** [Hoobachube/jacks-app-chest#26]
## Questions

1. What is the difference between the three and which should we be using for the CV page.
1. look in to when you should use `<i>` and `<b>` or `<em>` and `<strong>`

**Comment by Hoobachube** [comment]
**Section**
Typically has a heading.  It is not a generic container and should only appear in the outline of a document.
**Div**
A div is used when non other element is available.  This is generally only be used as a last resort.  Its main use is Class, Lang and title attributes to mark up elements.
**Article** 
Article tags must have a h1 tag. It is used for pieces of text within the document itself.  Such as; Post and magazine articles, etc.  It is used for independent section of content.

It is better practise to use the em and strong attributes as bold and italic are not very descriptive and may not always render correctly when used with different languages.
