### ISSUE TITLE
SPIKE - what does blur mean in javascript

### ISSUE THREAD

**Issue by alexw1983** [Hoobachube/jacks-app-chest#33]
## Questions

1. Go and look up what blur does in javascript

**Comment by Hoobachube** [comment]
A blur() event is away of removing the focus from an object.  For example an input can be made to fade once another area has been clicked on.  I its often used in conjunction with the focus() method which highlights the next input.  This can be a good way to guide the user through a series of actions.
Another use for both Blur and Focus is to validate the user input according to the coded criteria so alerts or warnings can appear to inform the user of any errors that they have entered.

**Comment by alexw1983** [comment]
Looks good can you throw together some example code that demonstrates this being used. Please show the onblur event as well.

**Comment by Hoobachube** [comment]
This example shows that when something has been entered into the field that does not follow the correct criteria an alert box will appear to inform the user that incorrect data has been entered.  For the purposes of this example there is no correct parameters so the alert box will always appear

```javascript
<input type="text" onblur="dataEntry()">

<script>
function dataEntry() {
  alert("Incorrect data Entered.");
}
</script>
```
