### ISSUE TITLE
SUDOKU - add number buttons

### ISSUE THREAD

**Issue by alexw1983** [Hoobachube/jacks-app-chest#41]
## Description

We want users to be able to enter values on to the grid. As per the design we want a row of buttons at the bottom of the page that when clicked enter that number in the selected square.

## Acceptance Criteria

1. When I click on one of the number buttons at the bottom of the page that number should appear in the selected box.
1. Buttons should be disabled if I have not yet selected a cell.

**Comment by Hoobachube** [comment]
A bit behind this week dude to big government audit at work.  Ive made the numbers appear but are having several issues that i'm hoping you can drop several hints to fix. 

1. Even though I've extended the container to encompass buttons I cant get them to line up with the grid
2. How do I create a break in between the buttons e.g. 1-5 on one line and 6-9 line line below
3. I have written the buttons individually which obviously means there is a lot of repeated code so would like a hint on how to reduce that.
4. Most importantly I am trying to work out how to get the button to appear on the selected cell.  I am pulling a blank on that one.

I will carry on trying to work it out but if you have a moment to throw some hints my way I would be grateful!
