### ISSUE TITLE
TEST - FIZZ BUZZ

### ISSUE THREAD

**Issue by alexw1983** [Hoobachube/jacks-app-chest#49]
## Description

FIZZBUZZ is a classic interview question in any programming language. It tests the basics.

## The Test

1. Write out to the console the numbers 1 to 15.
1. If the number is divisible by 3 write the word FIZZ instead of the number.
1. If the number is divisible by 5 write the word BUZZ instead of the number.
1. If the number is divisible by 5 and 3 then write the word FIZZBUZZ instead of the number.

## Expected output:
```
1
2
FIZZ
4
BUZZ
FIZZ
7
8
FIZZ
BUZZ
11
FIZZ
13
14
FIZBUZZ
```

**Comment by Hoobachube** [comment]
**FizzBuzz**

```javascript
let i = "";  // need empty quotes for the strings
for (let i = 1; i < 16; i++)  //  creates the loop of 1 to 15
  if (i % 3 === 0 && i % 5 === 0) {
    console.log("FizzBuzz");  //  multiples of 3 and 5 and the string response
  } else if (i % 3 === 0) {
    console.log("Fizz");
  } else if (i % 5 === 0) {
    console.log("Buzz");
  } else {
    console.log(i);
  } 
```
